const colors = {
  // 'transparent': 'transparent',

  // 'black': '#22292f',
  // 'grey-darkest': '#3d4852',
  // 'grey-darker': '#606f7b',
  // 'grey-dark': '#8795a1',
  // 'grey': '#b8c2cc',
  // 'grey-light': '#dae1e7',
  // 'grey-lighter': '#f1f5f8',
  // 'grey-lightest': '#f8fafc',
  // 'white': '#ffffff',

  // 'red-darkest': '#3b0d0c',
  // 'red-darker': '#621b18',
  // 'red-dark': '#cc1f1a',
  // 'red': '#e3342f',
  // 'red-light': '#ef5753',
  // 'red-lighter': '#f9acaa',
  // 'red-lightest': '#fcebea',

  // 'orange-darkest': '#462a16',
  // 'orange-darker': '#613b1f',
  // 'orange-dark': '#de751f',
  // 'orange': '#f6993f',
  // 'orange-light': '#faad63',
  // 'orange-lighter': '#fcd9b6',
  // 'orange-lightest': '#fff5eb',

  // 'yellow-darkest': '#453411',
  // 'yellow-darker': '#684f1d',
  // 'yellow-dark': '#f2d024',
  // 'yellow': '#ffed4a',
  // 'yellow-light': '#fff382',
  // 'yellow-lighter': '#fff9c2',
  // 'yellow-lightest': '#fcfbeb',

  // 'green-darkest': '#0f2f21',
  // 'green-darker': '#1a4731',
  // 'green-dark': '#1f9d55',
  // 'green': '#38c172',
  // 'green-light': '#51d88a',
  // 'green-lighter': '#a2f5bf',
  // 'green-lightest': '#e3fcec',

  // 'teal-darkest': '#0d3331',
  // 'teal-darker': '#20504f',
  // 'teal-dark': '#38a89d',
  // 'teal': '#4dc0b5',
  // 'teal-light': '#64d5ca',
  // 'teal-lighter': '#a0f0ed',
  // 'teal-lightest': '#e8fffe',

  // 'blue-darkest': '#12283a',
  // 'blue-darker': '#1c3d5a',
  // 'blue-dark': '#2779bd',
  // 'blue': '#3490dc',
  // 'blue-light': '#6cb2eb',
  // 'blue-lighter': '#bcdefa',
  // 'blue-lightest': '#eff8ff',

  // 'indigo-darkest': '#191e38',
  // 'indigo-darker': '#2f365f',
  // 'indigo-dark': '#5661b3',
  // 'indigo': '#6574cd',
  // 'indigo-light': '#7886d7',
  // 'indigo-lighter': '#b2b7ff',
  // 'indigo-lightest': '#e6e8ff',

  // 'purple-darkest': '#21183c',
  // 'purple-darker': '#382b5f',
  // 'purple-dark': '#794acf',
  // 'purple': '#9561e2',
  // 'purple-light': '#a779e9',
  // 'purple-lighter': '#d6bbfc',
  // 'purple-lightest': '#f3ebff',

  // 'pink-darkest': '#451225',
  // 'pink-darker': '#6f213f',
  // 'pink-dark': '#eb5286',
  // 'pink': '#f66d9b',
  // 'pink-light': '#fa7ea8',
  // 'pink-lighter': '#ffbbca',
  // 'pink-lightest': '#ffebef',
  'gray': {
    // '100': '#f7fafc',
    // '200': '#edf2f7',
    // '300': '#e2e8f0',
    // '400': '#cbd5e0',
    // '500': '#a0aec0',
    // '600': '#718096',
    // '700': '#4a5568',
    // '800': '#2d3748',
    // '900': '#1a202c'
  },
  'red': {
    // '100': '#fff5f5',
    // '200': '#fed7d7',
    // '300': '#feb2b2',
    // '400': '#fc8181',
    // '500': '#f56565',
    // '600': '#e53e3e',
    // '700': '#c53030',
    // '800': '#9b2c2c',
    // '900': '#742a2a'
  },
  'orange': {
    // '100': '#fffaf0',
    // '200': '#feebc8',
    // '300': '#fbd38d',
    // '400': '#f6ad55',
    // '500': '#ed8936',
    // '600': '#dd6b20',
    // '700': '#c05621',
    // '800': '#9c4221',
    // '900': '#7b341e'
  },
  'yellow': {
    // '100': '#fffff0',
    // '200': '#fefcbf',
    // '300': '#faf089',
    // '400': '#f6e05e',
    // '500': '#ecc94b',
    // '600': '#d69e2e',
    // '700': '#b7791f',
    // '800': '#975a16',
    // '900': '#744210'
  },
  'green': {
    // '100': '#f0fff4',
    // '200': '#c6f6d5',
    // '300': '#9ae6b4',
    // '400': '#68d391',
    // '500': '#48bb78',
    // '600': '#38a169',
    // '700': '#2f855a',
    // '800': '#276749',
    // '900': '#22543d'
  },
  'teal': {
    // '100': '#e6fffa',
    // '200': '#b2f5ea',
    // '300': '#81e6d9',
    // '400': '#4fd1c5',
    // '500': '#38b2ac',
    // '600': '#319795',
    // '700': '#2c7a7b',
    // '800': '#285e61',
    // '900': '#234e52'
  },
  'blue': {
    // '100': '#ebf8ff',
    // '200': '#bee3f8',
    // '300': '#90cdf4',
    // '400': '#63b3ed',
    // '500': '#4299e1',
    // '600': '#3182ce',
    // '700': '#2b6cb0',
    // '800': '#2c5282',
    // '900': '#2a4365'
  },
  'indigo': {
    // '100': '#ebf8ff',
    // '200': '#bee3f8',
  },
  'pink': {
  },
  'purple': {
  }
};

function spacing() {
  const range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 20, 24, 32, 40, 48, 56, 64, 72]
  const obj = {
    '1/2': null
  };
  range.forEach(item => {
    obj[item] = `${item * 0.25}rem`
  });
  return obj;
}

module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    extend: {
      colors
    },
  },
  variants: {
    // appearance: [],// ['responsive'],
    // backgroundAttachment: [],// ['responsive'],
    // backgroundColors: [],
    // backgroundPosition: [],// ['responsive'],
    // backgroundRepeat: [],// ['responsive'],
    // backgroundSize: [],// ['responsive'],
    // borderColors: [],
    borderRadius: [],
    borderStyle: [],
    borderWidths: [],
    boxShadow: [],
    cursor: [],
    // display: ['responsive'],
    flexbox: ['responsive'],
    // float: [],// ['responsive'],
    fonts: [], // ['responsive'],
    // fontWeights: [],
    height: ['responsive'],
    // leading: [],// ['responsive'],
    // lists: [],// ['responsive'],
    margin: ['responsive'],
    // maxHeight: ['responsive'],
    // maxWidth: ['responsive'],
    // minHeight: ['responsive'],
    // minWidth: ['responsive'],
    // negativeMargin: [],// ['responsive'],
    opacity: [],
    overflow: [],
    padding: ['responsive'],
    // pointerEvents: [],// ['responsive'],
    position: false,
    // resize: [],// ['responsive'],
    // shadows: [],
    // svgFill: [],// [],
    // svgStroke: [],// [],
    textAlign: ['responsive'],
    // textColors: [],
    textSizes: ['responsive'],
    textStyle: [],
    // tracking: [],// ['responsive'],
    // userSelect: [],
    // verticalAlign: [],
    // visibility: [],// ['responsive'],
    // whitespace: [],// ['responsive'],
    width: ['responsive'],
    zIndex: [],
  },
  plugins: [],
  prefix: 'tw-',
  important: true,
  separator: '-',
  corePlugins: {
    appearance: false,
    backgroundAttachment: false,
    backgroundColors: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderColors: false,
    borderOpacity: false,
    display: false,
    float: false,
    fontWeights: false,
    leading: false,// ['responsive'],
    lists: false,// ['responsive'],
    maxHeight: false,
    maxWidth: false,
    minHeight: false,
    minWidth: false,
    negativeMargin: false,// ['responsive'],
    pointerEvents: false,// ['responsive'],
    resize: false,// ['responsive'],
    shadows: false,
    svgFill: false,// [],
    svgStroke: false,// [],
    textColors: false,
    tracking: false,// ['responsive'],
    userSelect: false,
    verticalAlign: false,
    visibility: false,// ['responsive'],
    whitespace: false,// ['responsive'],
    transform: false,
    translate: false,
    scale: false,
    rotate: false,
    transformOrigin: false,
    skew: false,
    space: false,
    divideWidth: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    gradientColorStops: false,
    placeholderColor: false,
    placeholderOpacity: false,
    stroke: false,
    strokeWidth: false,
    fill: false,
    gap: false,
    columnGap: false,
    rowGap: false,
    gridColumn: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowEnd: false,
    gridRowStart: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    gridAutoFlow: false,
    transitionProperty: false,
    transitionDuration: false,
    transitionTimingFunction: false,
    transitionDelay: false,
    animation: false,
    clear: false,
    accessibility: false
  },
};
